
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Create a dummy Supabase client that won't be used
// All functionality has been moved to localStorage
export const supabase = null;

